[package]
name = "sassry"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [build]
# rustc-args = ["-A", "dead_code"]

[package.metadata.cargo-fmt]
before-build = true

[dependencies]
cassry = { path = "../cassry" }

# tags
serde = { version = "1.0.163", features = ["derive", "rc"] }
serde_with = "3.0.0"
derive_more = "0.99.17"

# tokio stream
tokio-tungstenite = { version = "0.21.0", features = [
    "__rustls-tls",
    "handshake",
    "rustls-tls-native-roots",
] }
tokio-stream = "0.1.15"
tokio-util = { version = "0.7.8", features = ["codec"] }

# webserver
axum = { version = "0.7.4", features = ["form", "json", "tokio", "ws"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
tower = { version = "0.4", features = ["full"] }

# others
base64 = "0.22.0"
bitflags = "2.2.1"
rand = "0.8.4"
url = "2.2.2"

ta = "0.5.0"
meval = "0.2"

# tls-listener = { version = "0.9.1", features = [
#     "rustls",
# ] }


